### ISSUE TITLE
Pilon java heap space memory issue

### ISSUE THREAD

**Issue by Thomieh73** [NorwegianVeterinaryInstitute/Bifrost#37]
While running Bifrost to assemble two `Campylobacter jejuni` genomes I had an error with Pilon.

This was the Bifrost command I ran:

    /work/projects/nn9305k/vi_src/Bifrost/run_track.sh asm_annot.nf asm_annot_template.config condaslurm 2019-10-18_asm

The command.sh file for the pilon step of the error:

    #!/bin/bash -ue
    if [ -f /cluster/bin/jobsetup ];
    then set +u; source /cluster/bin/jobsetup; set -u; fi

    export _JAVA_OPTIONS=-Xmx12G
    pilon --threads 16 --genome 17-Cjejuni-CCUG11284T_S130_spades_scaffolds_min500.fasta     --bam 17-Cjejuni-CCUG11284T_S130_mapped_sorted.bam --output 17-Cjejuni-CCUG11284T_S130_pilon_spades     --changes --vcfqe &> 17-Cjejuni-CCUG11284T_S130_pilon_spades.log

And the error from the pilon log file:

```
NODE_8_length_83250_cov_1091.076203:1-83250 log:
frags 17-Cjejuni-CCUG11284T_S130_mapped_sorted.bam: coverage 2377
Total Reads: 1622369, Coverage: 2377, minDepth: 238
Confirmed 83069 of 83155 bases (99.90%)
Corrected 0 snps; 0 ambiguous bases; corrected 0 small insertions totaling 0 bases, 0 small deletions totaling 0 bases
# Attempting to fill gaps
fix gap: NODE_8_length_83250_cov_1091.076203:77330-77424 77247 -83 +130 PartialFill TandemRepeat 291
# Attempting to fix local continuity breaks
# fix break: NODE_8_length_83250_cov_1091.076203:24221-24244 0 -0 +0 NoSolution
Finished processing NODE_8_length_83250_cov_1091.076203:1-83250
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at htsjdk.samtools.DefaultSAMRecordFactory.createBAMRecord(DefaultSAMRecordFactory.java:36)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:200)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:660)
        at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:780)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:634)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:628)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:598)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:831)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:821)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:787)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:544)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:518)
        at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at org.broadinstitute.pilon.BamFile.process(BamFile.scala:114)
at org.broadinstitute.pilon.GenomeRegion.processBam(GenomeRegion.scala:279)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$4$$anonfun$apply$3.apply(GenomeFile.scala:111)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$4$$anonfun$apply$3.apply(GenomeFile.scala:111)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$4.apply(GenomeFile.scala:111)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$4.apply(GenomeFile.scala:108)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
```

The error seems to be a memory error with the Java heap memory size.

**Comment by karinlag** [comment]
I have figured out that this option can be changed by doing

process.javaopts = "“-Xmx20G” 

If more than 20 G is needed, increase that. 

Thus closing.
